### ISSUE TITLE
No build-blocks

### ISSUE THREAD

**Issue by Sl4vP0weR** [theneolanders/resonite-voice-bridge#3]
![image](https://github.com/user-attachments/assets/472a6d89-0337-41a6-a23f-3af8dd73464e)

**Comment by Zetaphor** [comment]
Are you using the latest release? What OS? What browser/version? Do you see anything in the console?

**Comment by Sl4vP0weR** [comment]
The latest release.
Windows 11 latest 23H2
Tried Opera and Google Chrome, same.
Web-Server logging the requests, yes.

**Comment by Zetaphor** [comment]
Can you please provide the output of the console?
Can you also please capture an HAR?
Are you using a fresh copy of the latest release?

https://geekflare.com/har-file-creation-and-analysis/

**Comment by Sl4vP0weR** [comment]
Console log:
```
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [05/Aug/2024 16:35:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Aug/2024 16:35:52] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:52] "GET /static/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:52] "GET /static/editor.js HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:52] "GET /static/index.js HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Aug/2024 16:35:57] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:57] "GET /static/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:57] "GET /static/index.js HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:57] "GET /static/editor.js HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:35:58] "GET /static/favicon.ico HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:36:01] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:36:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Aug/2024 16:36:05] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:36:05] "GET /static/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:36:05] "GET /static/editor.js HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:36:05] "GET /static/index.js HTTP/1.1" 304 -
127.0.0.1 - - [05/Aug/2024 16:36:06] "GET /static/favicon.ico HTTP/1.1" 304 -
```

HAR: [localhost.har](https://github.com/user-attachments/files/16493119/localhost.txt)

Used fresh copy.

**Comment by Sl4vP0weR** [comment]
Fixed on my own by downgrading blockly version to `10.4.3` at [index.html](https://github.com/theneolanders/resonite-voice-bridge/blob/03b0cbb8d4af02c80a42d8cbed6d429c4a001e89/templates/index.html#L403) (`https://unpkg.com/blockly@10.4.3/blockly.min.js`)

**Comment by Zetaphor** [comment]
Thank you for digging into this, I have not had the time nor really the interest, as I don't have a Windows install and haven't used Resonite in months. I'll push a new release with a pinned version of the blockly dependency.
